### ISSUE TITLE
大佬可以添加一个查询api余额的功能吗

### ISSUE THREAD

**Issue by LingHime** [yi03/koishi-plugin-openai-api#1]
这样就不用自己上官网查余额了

**Comment by yi03** [comment]
加了，你看看有没有什么问题。刚发布，可能要等十几分钟插件市场才能看到，最新版是1.1.4。

**Comment by LingHime** [comment]
大佬你好，我这边使用查询余额的功能出现了报错，具体如下：
![image](https://user-images.githubusercontent.com/23625078/229356314-a7de0e4a-d317-47b6-bb2b-69aa2f4ff100.png)
日志如下：
```
2023-04-02 13:36:09 [W] command openai-api --balance
                        AxiosError: Request failed with status code 403
                            at settle (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:1268:12)
                            at Unzip.handleStreamEnd (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:2446:11)
                            at Unzip.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1359:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by yi03** [comment]
> 大佬你好，我这边使用查询余额的功能出现了报错，具体如下： ![image](https://user-images.githubusercontent.com/23625078/229356314-a7de0e4a-d317-47b6-bb2b-69aa2f4ff100.png) 日志如下：
> 
> ```
> 2023-04-02 13:36:09 [W] command openai-api --balance
>                         AxiosError: Request failed with status code 403
>                             at settle (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:1268:12)
>                             at Unzip.handleStreamEnd (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:2446:11)
>                             at Unzip.emit (node:events:525:35)
>                             at endReadableNT (node:internal/streams/readable:1359:12)
>                             at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> ```

我也偶尔会这样，然后过一会儿再查就好了，可能是openai的问题，因为我打开网页看余额的时候也有时会出错。另外最近openai封号封的厉害，我今天号被封了，打算这阵子不用这个插件了。

**Comment by LingHime** [comment]
> > 大佬你好，我这边使用查询余额的功能出现了报错，具体如下： ![image](https://user-images.githubusercontent.com/23625078/229356314-a7de0e4a-d317-47b6-bb2b-69aa2f4ff100.png) 日志如下：
> > ```
> > 2023-04-02 13:36:09 [W] command openai-api --balance
> >                         AxiosError: Request failed with status code 403
> >                             at settle (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:1268:12)
> >                             at Unzip.handleStreamEnd (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:2446:11)
> >                             at Unzip.emit (node:events:525:35)
> >                             at endReadableNT (node:internal/streams/readable:1359:12)
> >                             at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> > ```
> 
> 我也偶尔会这样，然后过一会儿再查就好了，可能是openai的问题，因为我打开网页看余额的时候也有时会出错。另外最近openai封号封的厉害，我今天号被封了，打算这阵子不用这个插件了。

好的，谢谢
